name: Flutter Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '18'

      - uses: subosito/flutter-action@v2
        with:
         flutter-version: '3.7.3'

      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk